spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect