logging:
  level:
    org:
      springframework:
        jpa: INFO
server:
  port: 8081
  error:
    include-message: always
spring:
  datasource:
    generate-unique-name: false
    password:
    username: sa
    url: jdbc:h2:mem:employee-db
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always
